# Global Database Connection Strings
# Used by the db-tool plugin
# Format: connection_name=connection_string

default=Server=localhost;Database=Eternity;User Id=root;Password=pentium1.2;Charset=utf8;ConvertZeroDateTime=True;
